services:
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: main
            MYSQL_USER: admin
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: 1234
        ports:
            - "3306:3306"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
            interval: 5s

    redis:
        image: redis:8-bookworm
        ports:
            - "6379:6379"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            timeout: 20s
            retries: 5
            interval: 3s

    main-server:
        build: .
        env_file:
            - .env.example
        environment:
            NODE_ENV: ${NODE_ENV:-development}
            MODE: main
            DB_HOST: mysql
            DB_PORT: 3306
            DB_USERNAME: admin
            DB_PASSWORD: 1234
            WORKER_HOST: redis
            WORKER_PORT: 6379
            LOG_LEVEL: INFO
            ACCESS_TOKEN_KEY: ${ACCESS_TOKEN_KEY}
            REFRESH_TOKEN_KEY: ${REFRESH_TOKEN_KEY}
        ports:
            - "4000:4000"
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:4000/sys/health"]
            interval: 10s
            timeout: 5s
            retries: 3

    worker-server:
        build: .
        env_file:
            - .env.example
        environment:
            NODE_ENV: ${NODE_ENV:-development}
            MODE: main
            DB_HOST: mysql
            DB_PORT: 3306
            DB_USERNAME: admin
            DB_PASSWORD: 1234
            WORKER_HOST: redis
            WORKER_PORT: 6379
            LOG_LEVEL: INFO
            ACCESS_TOKEN_KEY: ${ACCESS_TOKEN_KEY}
            REFRESH_TOKEN_KEY: ${REFRESH_TOKEN_KEY}
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:4000/sys/health"]
            interval: 10s
            timeout: 5s
            retries: 3
